//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectManagementSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovedProject
    {
        public int ApprovedProjectID { get; set; }
        public int project_id { get; set; }
        public int ProjectMang_id { get; set; }
        public int Cust_id { get; set; }
    
        public virtual user user { get; set; }
        public virtual project project { get; set; }
        public virtual user user1 { get; set; }
    }
}
