//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectManagementSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDRequest
    {
        public int Id { get; set; }
        public int User_ID { get; set; }
        public int proj_ID { get; set; }
        public int Rj_status { get; set; }
    
        public virtual project project { get; set; }
        public virtual user user { get; set; }
    }
}
