//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectManagementSys.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class projectMSysEntities : DbContext
    {
        public projectMSysEntities()
            : base("name=projectMSysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApprovedProject> ApprovedProjects { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<userType> userTypes { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<JDRequest> JDRequests { get; set; }
        public virtual DbSet<TLRequest> TLRequests { get; set; }
    
        public virtual ObjectResult<PM_PROJ_Result> PM_PROJ(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PM_PROJ_Result>("PM_PROJ", iDParameter);
        }
    
        public virtual ObjectResult<PM_REQ_Result> PM_REQ(Nullable<int> c_ID)
        {
            var c_IDParameter = c_ID.HasValue ?
                new ObjectParameter("C_ID", c_ID) :
                new ObjectParameter("C_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PM_REQ_Result>("PM_REQ", c_IDParameter);
        }
    
        public virtual ObjectResult<JD_ReQ_Result> JD_ReQ(Nullable<int> jD_ID)
        {
            var jD_IDParameter = jD_ID.HasValue ?
                new ObjectParameter("JD_ID", jD_ID) :
                new ObjectParameter("JD_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<JD_ReQ_Result>("JD_ReQ", jD_IDParameter);
        }
    
        public virtual ObjectResult<submitJD_Result> submitJD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<submitJD_Result>("submitJD");
        }
    
        public virtual ObjectResult<TL_ReQ_Result> TL_ReQ(Nullable<int> t_ID)
        {
            var t_IDParameter = t_ID.HasValue ?
                new ObjectParameter("T_ID", t_ID) :
                new ObjectParameter("T_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TL_ReQ_Result>("TL_ReQ", t_IDParameter);
        }
    }
}
