//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectManagementSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int Team_Id { get; set; }
        public int PM_ID { get; set; }
        public int TL_ID { get; set; }
        public int JD_ID { get; set; }
        public int Post_ID { get; set; }
    
        public virtual project project { get; set; }
    }
}
